String.toLocaleString({
	"en": {
	   "%game-intro"           : "Become a super-player with the<br><strong>Supreme 10 Mushroom Blend!</strong>",
      "%restart-button"       : "Retry",
      "%keep-playing-button"  : "Continue",
      "%retry-button"         : "Retry",
      "%game-won"             : "You win!",
      "%game-over"            : "Game over!",
      "%game-explanation"     : "<strong class=\"important\">HOW TO PLAY:</strong> Use your finger to move the tiles. When two identical mushrooms touch, they merge to form the next one.<br>Can you reach <strong>The Sage on the Mountain?</strong>",
      "%disclaimer"           : "disclaimer",
      "%credits"              : "www.sageonthemountain.uk",
      "%tweet1"               : "I scored \"",
      "%tweet2"               : "\" at 2048 Sage of the Mountain #hashtag",
      "%tile-legend"          : "<strong class=\"important\">Tile legend:</strong>",
      '%2'                    : 'Agaricus Blazei',
      '%4'                    : 'Shiitake',
      '%8'                    : 'Maitake',
      '%16'                   : 'Lion\'s Mane',
      '%32'                   : 'Cordyceps',
      '%64'                   : 'Poria Cocos',
      '%128'                  : 'Reishi',
      '%256'                  : 'Chaga',
      '%512'                  : 'Tremella',
      '%1024'                 : 'Black Fungus',
      '%2048'                 : 'The Sage',
      '%p0'                   : 'Agaricus Blazei',
      '%p4'                   : 'Shiitake',
      '%p8'                   : 'Maitake',
      '%p16'                  : 'Lion\'s Mane',
      '%p32'                  : 'Cordyceps',
      '%p64'                  : 'Poria Cocos',
      '%p128'                 : 'Reishi',
      '%p256'                 : 'Chaga',
      '%p512'                 : 'Tremella',
      '%p1024'                : 'Black Fungus',
      '%p2048'                : 'The Sage',
	}

});